### ISSUE TITLE
android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application

### ISSUE THREAD

**Issue by tstr007** [naivor/NaivorPlayer#1]
`android.view.WindowManager$BadTokenException: Unable to add window -- token null is not for an application

at android.view.ViewRootImpl.setView(ViewRootImpl.java:566)

at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:282)

at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)

at android.app.Dialog.show(Dialog.java:298)

at com.naivor.player.surface.DialogHolder.showNotWifiDialog(DialogHolder.java:116)

at com.naivor.player.VideoPlayer.requestPrepareSourceData(VideoPlayer.java:1175)

at com.naivor.player.surface.ControlView.start(ControlView.java:501)

at com.naivor.player.surface.ControlView$ComponentListener.onClick(ControlView.java:880)

at android.view.View.performClick(View.java:4780)

`

**Comment by naivor** [comment]
There needs  a  context  that  which  type  is  activity  when you  create  VideoPlayer，because  Dialog  needs  it  ，if  you  used  a  application  type  context , the  BadTokenException  occoured .

**Comment by tstr007** [comment]
What did I miss here ?
`package me.domain.naivorplayertest;


import android.support.v7.app.AppCompatActivity;
import com.naivor.player.VideoPlayer;
import com.naivor.player.constant.ScreenState;

import me.domain.naivorplayertest.R;

/**
 * NaivorPlayer 的使用例子
 */
public class NaivorPlayerActivity extends AppCompatActivity {

    private String testStream ;
    private String testStreamTitle ;

   private VideoPlayer videoPlayer ;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_naivorplayer_test);

        testStream = "https://bitdash-a.akamaihd.net/content/sintel/hls/playlist.m3u8";
        testStreamTitle = "Test Video Title";
         videoPlayer = findViewById(R.id.videoPlayer);
            //自动缓冲
            videoPlayer.setAutoPrepare(true);

            //加载封面
//            Glide.with(this)
//                    .load(DataRepo.VIDEO_COVER)
//                    .override(320, 240)
//                    .into(videoPlayer.getPreviewView());

            //设置播放源
            videoPlayer.setUpFullscreen(testStream, testStreamTitle);

            //开始播放

    }

    @Override
    protected void onResume() {
        super.onResume();

        videoPlayer.onResume();
    }

    @Override
    protected void onPause() {
        super.onPause();

        videoPlayer.onPause();
    }

    @Override
    protected void onDestroy() {
        videoPlayer.release();
        super.onDestroy();
    }

    @Override
    public void onBackPressed() {

        if (!videoPlayer.backPress()) {
            super.onBackPressed();
        }

    }
}
`

**Comment by naivor** [comment]
Oh,i 'm  sorry, it's  a bug  ,thanks for your  feedback,  and  i  do  suggest  you  choose  other  videoplayer ,this  only  has  a  beauteful  UI  more  than  Exoplayer2 , and  beause  of  myself  reason  , this  project  has  given  up , and  it  is   not  performance !
